
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
    Briefcase, Search, Filter, PlusCircle, Eye, Trash2, 
    Calendar, User, FileText, MoreVertical, ChevronDown, Download,
    AlertCircle, CheckCircle, Clock, XCircle, Activity
} from 'lucide-react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';

const API_URL = 'http://localhost:5000/api';

const EnterpriseCases = () => {
    const navigate = useNavigate();
    const { user } = useAuth();
    const [loading, setLoading] = useState(true);
    const [cases, setCases] = useState([]);
    const [searchTerm, setSearchTerm] = useState('');
    const [statusFilter, setStatusFilter] = useState('all');
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
        const fetchCases = async () => {
            try {
                const token = localStorage.getItem('token') || localStorage.getItem('forensic-token');
                const headers = token ? { Authorization: `Bearer ${token}` } : {};
                const response = await axios.get(`${API_URL}/cases`, { headers });
                
                const casesData = response.data.cases || response.data || [];
                setCases(Array.isArray(casesData) ? casesData : []);
            } catch (error) {
                console.error('Cases fetch error:', error);
                setCases([]);
            } finally {
                setLoading(false);
            }
        };

        fetchCases();
    }, []);

    if (!mounted) {
        return (
            <div className="min-h-[400px] flex items-center justify-center">
                <div className="w-12 h-12 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
            </div>
        );
    }

    if (loading) {
        return (
            <div className="min-h-[400px] flex items-center justify-center">
                <div className="w-12 h-12 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
            </div>
        );
    }

    // Filter cases based on search and status
    const filteredCases = (cases || []).filter(case_ => {
        const matchesSearch = case_.caseName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                            case_.caseId?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                            case_.investigatorName?.toLowerCase().includes(searchTerm.toLowerCase());
        
        const matchesStatus = statusFilter === 'all' || case_.status === statusFilter;
        
        return matchesSearch && matchesStatus;
    });

    const getStatusBadge = (caseObj) => {
        const status = caseObj.status;
        const statusConfig = {
            active: { color: 'bg-blue-500/20 text-blue-400 border-blue-500/30', icon: Clock, label: 'Active' },
            analyzing: { color: 'bg-indigo-500/20 text-indigo-400 border-indigo-500/30', icon: Activity, label: 'Analyzing' },
            completed: { color: 'bg-purple-500/20 text-purple-400 border-purple-500/30', icon: CheckCircle, label: 'Completed' },
            pending: { color: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30', icon: Clock, label: 'Pending Approval' },
            approved: { color: 'bg-green-500/20 text-green-400 border-green-500/30', icon: CheckCircle, label: 'Approved' },
            rejected: { color: 'bg-red-500/20 text-red-400 border-red-500/30', icon: AlertCircle, label: 'Rejected' },
            archived: { color: 'bg-gray-500/20 text-gray-400 border-gray-500/30', icon: XCircle, label: 'Archived' }
        };
        
        const config = statusConfig[status] || statusConfig.pending;
        const Icon = config.icon || Clock;
        
        return (
            <div className="flex flex-col gap-1">
                <span className={`inline-flex items-center gap-1 px-3 py-1 rounded-full text-[10px] font-bold uppercase border ${config.color}`}>
                    <Icon size={10} />
                    {config.label}
                </span>
                {status === 'rejected' && caseObj.remarks && (
                    <div className="text-[10px] text-red-400 bg-red-500/5 p-1.5 rounded border border-red-500/10 mt-1 max-w-[150px] italic">
                        <span className="font-bold">Remark:</span> {caseObj.remarks}
                    </div>
                )}
            </div>
        );
    };

    const handleDownloadReport = (case_) => {
        try {
            const reportContent = `
CASE REPORT
===========

Case Name: ${case_.caseName}
Case ID: ${case_.caseId}
Investigator: ${case_.investigatorName}
Date: ${case_.date}
Status: ${case_.status}
Evidence Count: ${case_.evidenceCount}

Generated by: Forensic Case Management System
Date: ${new Date().toLocaleDateString()}
            `;

            const blob = new Blob([reportContent], { type: 'text/plain' });
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `case-report-${case_.caseId}-${Date.now()}.txt`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            window.URL.revokeObjectURL(url);
        } catch (error) {
            console.error('Download report error:', error);
        }
    };

    const handleDeleteCase = async (caseId, caseName) => {
        if (!window.confirm(`Are you sure you want to delete case "${caseName}"? This action cannot be undone.`)) {
            return;
        }

        try {
            await axios.delete(`${API_URL}/cases/${caseId}`);
            
            // Remove case from local state
            setCases(cases.filter(c => c._id !== caseId));
            console.log('Case deleted successfully');
        } catch (error) {
            console.error('Delete case error:', error);
            // For demo purposes, still remove from local state even if API fails
            setCases(cases.filter(c => c._id !== caseId));
        }
    };

    return (
        <div className="p-6 space-y-6 animate-fadeInUp">
            {/* Page Header */}
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-black dark:text-white">Case Management</h1>
                    <p className="text-gray-400">Manage and track all forensic investigations</p>
                </div>
                {user?.role === 'investigator' && (
                    <button
                        onClick={() => navigate('/investigator/new-case')}
                        className="inline-flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-blue-500 to-blue-600 text-white rounded-lg hover:from-blue-600 hover:to-blue-700 transition-all duration-300 font-medium"
                    >
                        <PlusCircle size={18} />
                        Create Case
                    </button>
                )}
            </div>

            {/* Action Bar */}
            <div className="flex flex-col sm:flex-row gap-4">
                {/* Search Bar */}
                <div className="flex-1 relative">
                    <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={18} />
                    <input
                        type="text"
                        placeholder="Search cases by name, ID, or investigator..."
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                        className="w-full pl-10 pr-4 py-2 bg-gray-100 dark:bg-gray-800/50 border border-gray-300 dark:border-gray-700 rounded-lg text-black dark:text-white placeholder-gray-500 dark:placeholder-gray-500 focus:border-blue-500/50 focus:outline-none transition-all"
                    />
                </div>

                {/* Status Filter */}
                <div className="relative">
                    <select
                        value={statusFilter}
                        onChange={(e) => setStatusFilter(e.target.value)}
                        className="appearance-none pl-10 pr-8 py-2 bg-gray-100 dark:bg-gray-800/50 border border-gray-300 dark:border-gray-700 rounded-lg text-black dark:text-white focus:border-blue-500/50 focus:outline-none transition-all cursor-pointer"
                    >
                        <option value="all">All Status</option>
                        <option value="active">Active</option>
                        <option value="completed">Completed</option>
                        <option value="pending">Pending</option>
                        <option value="archived">Archived</option>
                    </select>
                    <Filter className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 pointer-events-none" size={18} />
                    <ChevronDown className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 pointer-events-none" size={16} />
                </div>
            </div>

            {/* Cases List */}
            <div className="rounded-2xl border backdrop-blur-sm" style={{ borderColor: 'rgba(255,255,255,0.08)' }}>
                <div className="overflow-x-auto">
                    <table className="w-full">
                        <thead>
                            <tr className="border-b" style={{ borderColor: 'rgba(255,255,255,0.08)' }}>
                                <th className="px-6 py-4 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">Case Details</th>
                                <th className="px-6 py-4 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">Investigator</th>
                                <th className="px-6 py-4 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">Date</th>
                                <th className="px-6 py-4 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">Evidence Count</th>
                                <th className="px-6 py-4 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">Status</th>
                                <th className="px-6 py-4 text-right text-xs font-medium text-gray-400 uppercase tracking-wider">Actions</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y" style={{ borderColor: 'rgba(255,255,255,0.08)' }}>
                            {filteredCases?.length > 0 ? (
                                filteredCases.map((case_) => (
                                    <tr 
                                        key={case_._id}
                                        className="hover:bg-gray-200 dark:hover:bg-gray-800/30 transition-colors"
                                    >
                                        <td className="px-6 py-4">
                                            <div className="flex items-center gap-3">
                                                <div className="w-10 h-10 rounded-lg bg-blue-500/20 flex items-center justify-center">
                                                    <Briefcase className="text-blue-400" size={18} />
                                                </div>
                                                <div>
                                                    <div className="font-medium text-black dark:text-white">{case_.caseName || 'Unnamed Case'}</div>
                                                    <div className="text-sm text-gray-400">{case_.caseId || 'N/A'}</div>
                                                </div>
                                            </div>
                                        </td>
                                        <td className="px-6 py-4">
                                            <div className="flex items-center gap-2">
                                                <User className="text-gray-400" size={16} />
                                                <span className="text-gray-700 dark:text-gray-300">{case_.investigatorName || 'Unassigned'}</span>
                                            </div>
                                        </td>
                                        <td className="px-6 py-4">
                                            <div className="flex items-center gap-2">
                                                <Calendar className="text-gray-400" size={16} />
                                                <span className="text-gray-300">
                                                    {case_.date ? new Date(case_.date).toLocaleDateString() : 'N/A'}
                                                </span>
                                            </div>
                                        </td>
                                        <td className="px-6 py-4">
                                            <div className="flex items-center gap-2">
                                                <FileText className="text-gray-400" size={16} />
                                                <span className="text-gray-700 dark:text-gray-300">{case_.evidenceCount || 0} files</span>
                                            </div>
                                        </td>
                                        <td className="px-6 py-4">
                                            {getStatusBadge(case_)}
                                        </td>
                                        <td className="px-6 py-4">
                                            <div className="flex items-center justify-end gap-2">
                                                <button
                                                    onClick={() => navigate(`${case_._id}`)}
                                                    className="p-2 rounded-lg hover:bg-gray-700/50 transition-colors"
                                                    title="View Details"
                                                >
                                                    <Eye className="text-gray-400" size={16} />
                                                </button>
                                                <button
                                                    onClick={() => handleDownloadReport(case_)}
                                                    className="p-2 rounded-lg hover:bg-gray-700/50 transition-colors"
                                                    title="Download Report"
                                                >
                                                    <Download className="text-gray-400" size={16} />
                                                </button>
                                                {user?.role === 'investigator' && (
                                                    <button
                                                        onClick={() => handleDeleteCase(case_._id, case_.caseName)}
                                                        className="p-2 rounded-lg hover:bg-red-500/20 text-red-400 transition-colors"
                                                        title="Delete Case"
                                                    >
                                                        <Trash2 size={16} />
                                                    </button>
                                                )}
                                            </div>
                                        </td>
                                    </tr>
                                ))
                            ) : (
                                <tr>
                                    <td colSpan="6" className="px-6 py-12 text-center text-gray-500">
                                        No cases found matching your criteria.
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Pagination (if needed) */}
            {filteredCases.length > 10 && (
                <div className="flex items-center justify-between">
                    <div className="text-sm text-gray-400">
                        Showing {filteredCases.length} cases
                    </div>
                    <div className="flex items-center gap-2">
                        <button className="px-3 py-1 bg-gray-200 dark:bg-gray-800/50 border border-gray-300 dark:border-gray-700 rounded-lg text-gray-600 dark:text-gray-400 hover:bg-gray-300 dark:hover:bg-gray-700/50 transition-colors">
                            Previous
                        </button>
                        <button className="px-3 py-1 bg-blue-500 text-white rounded-lg">
                            1
                        </button>
                        <button className="px-3 py-1 bg-gray-200 dark:bg-gray-800/50 border border-gray-300 dark:border-gray-700 rounded-lg text-gray-600 dark:text-gray-400 hover:bg-gray-300 dark:hover:bg-gray-700/50 transition-colors">
                            Next
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
};

export default EnterpriseCases;
